package modules

import (
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/SentinelXofficial/sxel/pkg/core"
)

func fakeWAFServer(handler http.HandlerFunc) *httptest.Server {
	return httptest.NewServer(handler)
}

func TestAutoDetectWAF(t *testing.T) {
	cases := []struct {
		name       string
		handler    http.HandlerFunc
		wantVendor string
	}{
		{"cloudflare header", func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Server", "cloudflare")
			w.Header().Set("CF-Ray", "abc123-SIN")
			fmt.Fprint(w, "hello")
		}, "Cloudflare"},
		{"safedog cookie", func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Set-Cookie", "safedog-flow-item=1; Path=/")
			fmt.Fprint(w, "hello")
		}, "Safedog"},
		{"incapsula body", func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(403)
			fmt.Fprint(w, "Incapsula incident id: 123")
		}, "Incapsula"},
		{"modsecurity content", func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(403)
			fmt.Fprint(w, "This error was generated by Mod_Security")
		}, "ModSecurity"},
		{"awswaf header", func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("X-AMZ-ID", "abc")
			fmt.Fprint(w, "ok")
		}, "AWS Elastic Load Balancer"},
		{"wordfence content", func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(403)
			fmt.Fprint(w, "Generated by Wordfence")
		}, "Wordfence"},
		{"fastly header", func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("X-Fastly-Request-ID", "f0o1b2")
			fmt.Fprint(w, "ok")
		}, "Fastly"},
		{"generic blocked", func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(403)
			fmt.Fprint(w, "Access denied, request blocked")
		}, "Unknown WAF"},
		{"yunjiasu header", func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Server", "yunjiasu-nginx")
			fmt.Fprint(w, "ok")
		}, "Yunjiasu"},
		{"fortiweb cookie", func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Set-Cookie", "FORTIWAFSID=abc; Path=/")
			fmt.Fprint(w, "ok")
		}, "FortiWeb"},
		{"kona header", func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Server", "AkamaiGHost")
			fmt.Fprint(w, "ok")
		}, "Kona SiteDefender"},
		{"kemp compound", func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("X-ServedBy", "KEMP-LM")
			w.WriteHeader(403)
			fmt.Fprint(w, "<title>403 Forbidden</title>")
		}, "Kemp LoadMaster"},
		{"denyall reason", func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(200)
			fmt.Fprint(w, "page")
		}, ""},
		{"no waf", func(w http.ResponseWriter, r *http.Request) {
			fmt.Fprint(w, "normal page")
		}, ""},
	}
	for _, c := range cases {
		srv := fakeWAFServer(c.handler)
		cfg := &core.Config{}
		res := AutoDetectWAF(srv.Client(), cfg, srv.URL+"/?a=1")
		if res.Detected && res.Vendor != c.wantVendor {
			t.Errorf("%s: got vendor %q want %q", c.name, res.Vendor, c.wantVendor)
		}
		if !res.Detected && c.wantVendor != "" {
			t.Errorf("%s: expected detection of %q", c.name, c.wantVendor)
		}
		srv.Close()
	}
}
